uint32 uart_baud                      #uart baudrate
uint32 can_baud                       #cam baudrate
uint32 device_address                 #device address
uint32 send_time_interval             #send time interval every group
uint32 send_mode                      #send mode(active or passive)
uint32[16] send_config_group          #16 group
uint32 inquire_config                 #query group
uint32 beep_enable                    #beep enable
uint32 alarm_distance  
uint32 uart_distance_send_enable
uint32 uart_alarm_send_enable
uint32 can_distance_send_enable
uint32 can_alarm_send_enable
#uint32 serial                         #serial number
#uint32 crc_sum                        #crc sum
